
#全局配置
server:
  servlet:
    # 项目contextPath，一般在正式发布版本中，我们不配置
    context-path: /
    # session最大超时时间(分钟)，默认为30
    session:
      timeout: 60m

#日志配置 等级由低到高：debug<info<warn<Error<Fatal
logging:
  level:
    com.geekcattle : debug
  file:
    name: "${user.home}/logs/spring-boot-logging.log"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor/actuator
  endpoint:
    health:
      show-details: always

  # 使用druid数据源
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: false
      validation-query: SELECT 'x'
  #json配置
  jackson:
    time-zone : Asia/Chongqing
    date-format : yyyy-MM-dd HH:mm:ss
    joda-date-time-format : yyyy-MM-dd HH:mm:ss
  # REDIS基础配置
  redis:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active : 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）毫秒
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle : 8
        # 连接池中的最小空闲连接
        min-idle : 0
      # 连接超时时间（毫秒）
    timeout : 500ms

#mybaties配置
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml
  type-aliases-package: com.example.coolrabbit.entity

#mapper配置
mapper:
  plugin : tk.mybatis.mapper.generator.MapperPlugin
  not-empty: false
  mappers : com.example.coolrabbit.dao

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

shiro:
  session:
    #shiro session前缀
    session-prefix : "shiro-redis-session"
    #shiro session 在redis过期时间是(分钟)
    session-time : 1800
  cache:
    #shiro缓存前缀
    cache-prefix : "shiro-redis-cache"
    #shiro缓存在redis过期时间是(分钟)
    cache-time : 180
#JWT配置
jwt:
  ##认证名称
  header : "authorization"
  ##加密向量
  secret : "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
  ##token过期时间一天(秒)
  expiration : 7200
  ##refresh_token过期时间一天(秒)
  refresh_expiration : 86400
  ##Tokenu前缀
  token.head : "Bearer"


#开发环境
spring:
  profiles: dev
  datasource:
    name : coolrabbit
    username  : root
    password  :
    url : jdbc:mysql://localhost:3306/coderabbit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    database : 0
    host : 127.0.0.1
    port : 6379
    password :

---

#测试环境
spring:
  profiles: pro
  datasource:
    name : coolrabbit
    username  : root
    password  :
    url : jdbc:mysql://localhost:3306/geekcattle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    database : 0
    host : 127.0.0.1
    port : 6379
    password :
server:
  port: 8001

---



